name: PHP Coding Standards

on:
  push:
    branches:
      - master
      - 'test-workflow'
  workflow_dispatch:

jobs:
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.0
        name: 'Checkout repository'

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3.3.2
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.26.0 
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr

      - name: Log debug information
        run: |
          php --version
          composer --version

      - name: Install Composer dependencies
        run: |
            composer install --prefer-dist --no-suggest --no-progress --no-ansi --no-interaction
            echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Run & fix PHP Code Sniffer
        uses: shalior/wordpress-phpcs-action@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          use_default_configuration_file: true
          phpcs_args: '-n' 

      - uses: stefanzweifel/git-auto-commit-action@v4 
        with:
          commit_message: Fix PHPCS errors

